{% set name = "github-activity" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/github_activity-{{ version }}.tar.gz
  sha256: 99cbe1a817b3ad0bd0d90cdb76313809bf7dad29e7d06e01eb0b28c1adc3d0dd

build:
  entry_points:
    - github-activity = github_activity.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - git
    - markdown
    - numpy
    - pandas
    - python >=3.6
    - python-dateutil
    - requests
    - tqdm

test:
  imports:
    - github_activity
  commands:
    - pip check
    - github-activity --help
  requires:
    - pip

about:
  home: https://github.com/executablebooks/github-activity
  summary: Simple markdown changelogs for GitHub repositories
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - manics
    - consideratio
    - blink1073
