{% set name = "github-activity" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/github_activity-{{ version }}.tar.gz
  sha256: 3bdf5a9d5108ad8cce44fdccf8d9d4268d67307866b9e4e438c8c6edc3d012bf

build:
  entry_points:
    - github-activity = github_activity.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - git
    - markdown
    - numpy
    - pandas
    - python >={{ python_min }}
    - python-dateutil
    - requests
    - tqdm

test:
  imports:
    - github_activity
  commands:
    - pip check
    - github-activity --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/executablebooks/github-activity
  summary: Simple markdown changelogs for GitHub repositories
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - manics
    - consideratio
    - blink1073
